name: twitter_oembed_api
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  import_sorter: ^4.6.0